### ISSUE TITLE
SCION DP as IPv6 routing header - discussion

### ISSUE THREAD

**Issue by nicorusti** [scionassociation/scion-components_I-D#13]
As discussed in https://github.com/scionassociation/scion-components_I-D/pull/12#pullrequestreview-1326484875 by @matzf and in https://github.com/scionproto/scion/discussions/4324 : 

> I think it would be worth expanding on this topic and the challenges it poses:
> The main challenges are:
> * intra-domain forwarding needs to be revisited (either make intra-domain routing infra IPv6+SCION aware, use other routing headers on top for local forwarding (SRv6), or encapsulate).
> * addressing: SCION endpoint needs AS information to query path to destination; IPv6 addresses don't contain this information.  keep separate SCION addresses, assign special address ranges that encode AS number, or design (secure) mapping from address ranges to ASes.

**Comment by matzf** [comment]
> intra-domain forwarding needs to be revisited (either make intra-domain routing infra IPv6+SCION aware, use other routing headers on top for local forwarding (SRv6), or encapsulate).

Turns out this is already solved! :wink: We can use the same approach used with the Segment Routing Header (which I had misunderstood). See https://github.com/scionproto/scion/discussions/4324#discussioncomment-5265015

**Comment by nicorusti** [comment]
Closing this issue as discussion is advancing in https://github.com/scionproto/scion/discussions/4324
